version: "3"

services:
  api:
    build: .
    container_name: api
    ports:
      - 8000:8000
    env_file:
      - './api/api.env'
    volumes:
      - './api:/api/api'

networks:
    default:
        driver: bridge